# Generated by Django 6.1.1 on 2026-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('s_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
